# Generated by Django 5.0.6 on 2024-10-13 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallFriends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='file_html',
            field=models.FileField(upload_to='generate/renders/html/'),
        ),
        migrations.AlterField(
            model_name='generate',
            name='file_pdf',
            field=models.FileField(upload_to='generate/renders/pdf/'),
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Akkaunt',
                'verbose_name_plural': 'Telegram Akkauntlar',
            },
        ),
    ]
